In [1]:
# installing required modules
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /home/fahad/.local/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /home/fahad/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/fahad/.local/lib/python3.8/site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/fahad/.local/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/fahad/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Requirement already satisfied: numpy in /home/fahad/.local/lib/python3.8/site-packages (1.24.3)

In [6]:
# reading the csv file which hold our data
import pandas as pd
df = pd.read_csv('fahad_data.csv')
df.head(30)

,Kingdom of Saudi Arabia,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Faculty,: Faculty of Computer Science & I,NaN,NaN,NaN,NaN
1,Jazan University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Student Name,:,FAHAD ALI M ALMAKIN,NaN,NaN,NaN,Department : Information Technology and Sec,NaN,NaN,NaN,NaN,NaN
3,Deanship of Admissions & Registration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Student ID,: 202002381,NaN,NaN,NaN,NaN,Major,: Information Systems,NaN,NaN,NaN,NaN
5,NaN,NaN,Status,:,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Page,:,1,To,4.0
7,First Semester Year 20201,NaN,StatusActive,Regular,Major Information Sy,NaN,First Semester Year 20211,NaN,StatusActive,Regular,Major Information Sy,NaN,NaN,NaN
8,course code,NaN,course name,NaN,Grade Hrs,Pts,course code,NaN,course name,NaN,Grade Hrs,Pts,NaN,NaN
9,100MATH-3,Mathematics,NaN,NaN,D,3,6,ARB101-2,Arabic Language Skills,NaN,A+,2,10,NaN
10,CSC101-3,Introduction to Computer,NaN,NaN,C+,3,10.5,SLM103-2,Islamic Culture III,NaN,A+,2,10,NaN
11,SLM101-2,Islamic Culture I,NaN,NaN,A,2,9.5,111INFS-3,Introduction to Information System,NaN,A+,3,15,NaN
12,103ENG-6,Intensive English Course 1,NaN,NaN,B+,6,27,112COMP-3,Programming 2,NaN,B+,3,13.5,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,201PHYS-4,Principles of Physics,NaN,NaN,C+,4,14,NaN
14,Hrs,AHRS,EHRS,QHRS,QPTS,GPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Current,14,14,14,53,3.79,Hrs,AHRS,EHRS,QHRS,QPTS,GPA,NaN,NaN
16,Cumulative,14,14,14,53,3.79,Current,14,14,14,62.5,4.46,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,Cumulative,42,42,42,184,4.38,NaN,NaN
18,Second Semester Year 20202,NaN,StatusActive,Regular,Major Information Sy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,course code,NaN,course name,NaN,Grade Hrs,Pts,Second Semester Year 20212,NaN,StatusActive,Regular,Major Information Sy,NaN,NaN,NaN
20,011COMP-3,Programming 1,NaN,NaN,A+,3,15,course code,course name,NaN,Grade Hrs,Pts,NaN,NaN
21,102MATH-3,Matrix Algebra,NaN,NaN,B+,3,13.5,ARB102-2,Arabic Writing,NaN,B+,2,9,NaN
22,SLM102-2,Islamic Culture II,NaN,NaN,A+,2,10,SLM104-2,Islamic Culture IV,NaN,A+,2,10,NaN
23,104ENGL-6,Intensive English Course 2,NaN,NaN,A+,6,30,112INFS-3,Management Information Systems,NaN,A+,3,15,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,201MATH-3,Differentiation & Integration,NaN,NaN,B,3,12,NaN
25,Hrs,AHRS,EHRS,QHRS,QPTS,GPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,206MATH-3,Discrete mathematics,NaN,NaN,A,3,14.25,NaN
27,Current,14,14,14,68.5,4.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,213ADM-3,Management principles and methods,NaN,NaN,B,3,12,NaN
29,Cumulative,28,28,28,121.5,4.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# grade A+ list
a_p = []

# grade A list
a_ = []

# grade B+ list
b_p = []

# grade B list
b_ = []

# grade C+ list
c_p = []


# grade C list
c_ = []


# grade D+ list
d_p = []


# grade D list
d_ = []

# grade D list
f_ = []

In [12]:
for index, row in df.iterrows():  # Iterate over rows of the DataFrame
    for value in row:  # Iterate over values in the row
        if value == 'A+':  # Check if value is 'A+'
            a_p.append(value)  # If 'A+' is found, append it to a_p list

TypeError: sequence item 2: expected str instance, Series found